theme: jekyll-theme-slate
title: RPN Calculator
description: Reverse Polish Notation computing engine and PapajScript intepreter
show_downloads: true
#github:
#  zip_url: https://github.com/RooiGevaar19/RPNCalculator/releases/download/v050-stable/RPNCalculator050.zip
