#theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist@v0.1.0
 plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
title: RPN Calculator
description: Reverse Polish Notation computing engine and PapajScript intepreter
#logo: wall1.png
logo: icon256_1.png
show_downloads: false
#github:
#  zip_url: https://github.com/RooiGevaar19/RPNCalculator/releases/download/v050-stable/RPNCalculator050.zip
